/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcf.jform;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import rcf.aula.Salario;
import rcf.exceptions.CampoVazioException;

/**
 *
 * @author 00348046
 */
public class Desutilidade extends javax.swing.JFrame {
    
    /**
     * Creates new form Desutilidade
     */
    public Desutilidade() {
        initComponents();
        painelAulas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criticaCampo = new javax.swing.JDialog();
        painelCritica = new javax.swing.JPanel();
        labelCritica = new javax.swing.JLabel();
        painelMain = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        tituloMain = new javax.swing.JLabel();
        painelAulas = new javax.swing.JPanel();
        botaoVoltarInicio = new javax.swing.JButton();
        painelSalario = new javax.swing.JPanel();
        labelTituloSalario = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelSalario = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        divisor = new javax.swing.JSeparator();
        labelNomeResultado = new javax.swing.JLabel();
        labelSalarioBrutoAtual = new javax.swing.JLabel();
        botaoCalcular = new javax.swing.JButton();
        labelIRSalarioAtual = new javax.swing.JLabel();
        labelINSSSalarioAtual = new javax.swing.JLabel();
        labelSalarioLiquidoAtual = new javax.swing.JLabel();
        labelSalarioBrutoAumento = new javax.swing.JLabel();
        labelIRSalarioAumento = new javax.swing.JLabel();
        labelINSSSalarioAumento = new javax.swing.JLabel();
        labelSalarioLiquidoAumento = new javax.swing.JLabel();

        criticaCampo.setModal(true);
        criticaCampo.setPreferredSize(new java.awt.Dimension(279, 67));
        criticaCampo.setResizable(false);
        criticaCampo.setSize(new java.awt.Dimension(279, 67));

        painelCritica.setPreferredSize(new java.awt.Dimension(279, 67));

        javax.swing.GroupLayout painelCriticaLayout = new javax.swing.GroupLayout(painelCritica);
        painelCritica.setLayout(painelCriticaLayout);
        painelCriticaLayout.setHorizontalGroup(
            painelCriticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        painelCriticaLayout.setVerticalGroup(
            painelCriticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        labelCritica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCritica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout criticaCampoLayout = new javax.swing.GroupLayout(criticaCampo.getContentPane());
        criticaCampo.getContentPane().setLayout(criticaCampoLayout);
        criticaCampoLayout.setHorizontalGroup(
            criticaCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCritica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addGroup(criticaCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelCritica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        criticaCampoLayout.setVerticalGroup(
            criticaCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criticaCampoLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(labelCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(criticaCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelCritica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 280));

        painelMain.setFocusable(false);
        painelMain.setMaximumSize(new java.awt.Dimension(400, 280));
        painelMain.setMinimumSize(new java.awt.Dimension(400, 280));
        painelMain.setPreferredSize(new java.awt.Dimension(400, 280));

        botaoIniciar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        botaoIniciar.setForeground(java.awt.SystemColor.controlDkShadow);
        botaoIniciar.setText("Iniciar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        tituloMain.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        tituloMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMain.setLabelFor(this);
        tituloMain.setText("Desutilidade");

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloMain))
                .addGap(90, 90, 90))
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tituloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(botaoIniciar)
                .addGap(56, 56, 56))
        );

        painelAulas.setMaximumSize(new java.awt.Dimension(400, 280));
        painelAulas.setMinimumSize(new java.awt.Dimension(400, 280));
        painelAulas.setPreferredSize(new java.awt.Dimension(400, 280));

        botaoVoltarInicio.setLabel("Voltar");
        botaoVoltarInicio.setPreferredSize(new java.awt.Dimension(80, 25));
        botaoVoltarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarInicioActionPerformed(evt);
            }
        });

        labelTituloSalario.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        labelTituloSalario.setForeground(new java.awt.Color(0, 51, 153));
        labelTituloSalario.setText("Calculo Aumento de Salario");

        labelNome.setText("Seu nome:");

        labelSalario.setText("Digite seu salário:");

        labelNomeResultado.setText("Seu nome: ");

        labelSalarioBrutoAtual.setText("Seu salário bruto atual: ");

        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        labelIRSalarioAtual.setText("IR do salário atual: ");

        labelINSSSalarioAtual.setText("INSS do salário atual: ");

        labelSalarioLiquidoAtual.setText("Seu salário liquido atual: ");

        labelSalarioBrutoAumento.setText("Seu salário bruto com aumento: ");

        labelIRSalarioAumento.setText("IR do salário com aumento: ");

        labelINSSSalarioAumento.setText("INSS do salário com aumento: ");

        labelSalarioLiquidoAumento.setText("Seu salário liquido com aumento: ");

        javax.swing.GroupLayout painelSalarioLayout = new javax.swing.GroupLayout(painelSalario);
        painelSalario.setLayout(painelSalarioLayout);
        painelSalarioLayout.setHorizontalGroup(
            painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSalarioLayout.createSequentialGroup()
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSalarioLayout.createSequentialGroup()
                        .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelSalarioLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(labelTituloSalario))
                            .addGroup(painelSalarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelNomeResultado)))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(painelSalarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divisor)
                            .addGroup(painelSalarioLayout.createSequentialGroup()
                                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSalario)
                                    .addComponent(labelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoNome)
                                    .addComponent(campoSalario))
                                .addGap(10, 10, 10)
                                .addComponent(botaoCalcular))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSalarioLayout.createSequentialGroup()
                                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSalarioBrutoAtual)
                                    .addComponent(labelIRSalarioAtual)
                                    .addComponent(labelINSSSalarioAtual)
                                    .addComponent(labelSalarioLiquidoAtual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIRSalarioAumento)
                                    .addComponent(labelSalarioBrutoAumento)
                                    .addComponent(labelINSSSalarioAumento)
                                    .addComponent(labelSalarioLiquidoAumento))
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        painelSalarioLayout.setVerticalGroup(
            painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomeResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalarioBrutoAtual)
                    .addComponent(labelSalarioBrutoAumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIRSalarioAtual)
                    .addComponent(labelIRSalarioAumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelINSSSalarioAtual)
                    .addComponent(labelINSSSalarioAumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalarioLiquidoAtual)
                    .addComponent(labelSalarioLiquidoAumento))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelAulasLayout = new javax.swing.GroupLayout(painelAulas);
        painelAulas.setLayout(painelAulasLayout);
        painelAulasLayout.setHorizontalGroup(
            painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAulasLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(botaoVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAulasLayout.setVerticalGroup(
            painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAulasLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(botaoVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelAulasLayout.createSequentialGroup()
                    .addComponent(painelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(painelAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        // TODO add your handling code here:
        painelMain.setVisible(false);
        painelAulas.setVisible(true);
        prepareTelaSalario(false);
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoVoltarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarInicioActionPerformed
        // TODO add your handling code here:
        painelAulas.setVisible(false);
        painelMain.setVisible(true);
        initComponents();
    }//GEN-LAST:event_botaoVoltarInicioActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        // TODO add your handling code here:
        try {
            campoIsEmpty(campoNome, labelNome);
            campoIsEmpty(campoSalario, labelSalario);
            Salario salarioCalss = new Salario();
            float salarioAumentado = salarioCalss.aumentoSalario(Float.valueOf(campoSalario.getText()));
            labelNomeResultado.setText(concatenaTextLabelTela(labelNomeResultado, campoNome.getText()));
            labelSalarioBrutoAtual.setText(concatenaTextLabelTela(labelSalarioBrutoAtual, campoSalario.getText()));
            labelIRSalarioAtual.setText(concatenaTextLabelTela(labelIRSalarioAtual, String.valueOf(salarioCalss.calculaIR(Float.valueOf(campoSalario.getText())))));
            labelINSSSalarioAtual.setText(concatenaTextLabelTela(labelINSSSalarioAtual, String.valueOf(salarioCalss.calculaINSS(Float.valueOf(campoSalario.getText())))));
            labelSalarioLiquidoAtual.setText(concatenaTextLabelTela(labelSalarioLiquidoAtual, String.valueOf(
                    // Calculo de subtração
                    Float.valueOf(campoSalario.getText()) - 
                    salarioCalss.calculaINSS(Float.valueOf(campoSalario.getText())) - 
                    salarioCalss.calculaIR(Float.valueOf(campoSalario.getText()))
            )));
            labelSalarioBrutoAumento.setText(concatenaTextLabelTela(labelSalarioBrutoAumento, String.valueOf(salarioAumentado)));
            labelIRSalarioAumento.setText(concatenaTextLabelTela(labelIRSalarioAumento, String.valueOf(salarioCalss.calculaIR(salarioAumentado))));
            labelINSSSalarioAumento.setText(concatenaTextLabelTela(labelINSSSalarioAumento, String.valueOf(salarioCalss.calculaINSS(salarioAumentado))));
            labelSalarioLiquidoAumento.setText(concatenaTextLabelTela(labelSalarioLiquidoAumento, String.valueOf(
                    // Calculo de subtração
                    salarioAumentado - 
                    salarioCalss.calculaINSS(salarioAumentado) - 
                    salarioCalss.calculaIR(salarioAumentado)
            )));
            painelSalario.setSize(400, 400);
            painelAulas.setSize(400, 400);
            prepareTelaSalario(true);
            
        } catch (NumberFormatException numberException){
            labelCritica.setText(numberException.getMessage());
            criticaCampo.setVisible(true);
        } catch (CampoVazioException campoException){
            labelCritica.setText(campoException.getMessage());
            criticaCampo.setVisible(true);            
        }
    }//GEN-LAST:event_botaoCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*
            Autor: @Rodrigo
            Descrição: Seleciona um tema personalidado
            Biblioteca: flatlaf-demo-3.4.jar
            */
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            //    if ("Nimbus".equals(info.getName())) {
            //       javax.swing.UIManager.setLookAndFeel(info.getClassName());
            //        break;
            //    }
            //}
        //} catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desutilidade().setVisible(true);
            }
        });
    }
    
    /*
        Meus métodos    
    */
    
    public void campoIsEmpty(JTextField campo, JLabel label) throws CampoVazioException{
        if(campo.getText().isEmpty()){
            throw new CampoVazioException(label.getText());
        }
    }
    
    public void prepareTelaSalario(boolean isVisivel){
        labelINSSSalarioAtual.setVisible(isVisivel);
        labelINSSSalarioAumento.setVisible(isVisivel);
        labelIRSalarioAtual.setVisible(isVisivel);
        labelIRSalarioAumento.setVisible(isVisivel);
        labelNomeResultado.setVisible(isVisivel);
        labelSalarioBrutoAtual.setVisible(isVisivel);
        labelSalarioBrutoAumento.setVisible(isVisivel);
        labelSalarioLiquidoAtual.setVisible(isVisivel);
        labelSalarioLiquidoAumento.setVisible(isVisivel);
    }
    
    public String concatenaTextLabelTela(JLabel label, String valor){
        return label.getText() + " " + valor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoVoltarInicio;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JDialog criticaCampo;
    private javax.swing.JSeparator divisor;
    private javax.swing.JLabel labelCritica;
    private javax.swing.JLabel labelINSSSalarioAtual;
    private javax.swing.JLabel labelINSSSalarioAumento;
    private javax.swing.JLabel labelIRSalarioAtual;
    private javax.swing.JLabel labelIRSalarioAumento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeResultado;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSalarioBrutoAtual;
    private javax.swing.JLabel labelSalarioBrutoAumento;
    private javax.swing.JLabel labelSalarioLiquidoAtual;
    private javax.swing.JLabel labelSalarioLiquidoAumento;
    private javax.swing.JLabel labelTituloSalario;
    private javax.swing.JPanel painelAulas;
    private javax.swing.JPanel painelCritica;
    private javax.swing.JPanel painelMain;
    private javax.swing.JPanel painelSalario;
    private javax.swing.JLabel tituloMain;
    // End of variables declaration//GEN-END:variables
}
