/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcf.jform;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author 00348046
 */
public class Desutilidade extends javax.swing.JFrame {

    /**
     * Creates new form Desutilidade
     */
    public Desutilidade() {
        initComponents();
        painelAulas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMain = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        tituloMain = new javax.swing.JLabel();
        painelAulas = new javax.swing.JPanel();
        botaoVoltarInicio = new javax.swing.JButton();
        tabPrincipal = new javax.swing.JTabbedPane();
        tabAula1 = new javax.swing.JTabbedPane();
        tabAula2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setPreferredSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 280));

        painelMain.setFocusable(false);
        painelMain.setMaximumSize(new java.awt.Dimension(400, 280));
        painelMain.setMinimumSize(new java.awt.Dimension(400, 280));
        painelMain.setPreferredSize(new java.awt.Dimension(400, 280));

        botaoIniciar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        botaoIniciar.setForeground(java.awt.SystemColor.controlDkShadow);
        botaoIniciar.setText("Iniciar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        tituloMain.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        tituloMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMain.setLabelFor(this);
        tituloMain.setText("Desutilidade");

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloMain))
                .addGap(90, 90, 90))
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tituloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(botaoIniciar)
                .addGap(56, 56, 56))
        );

        painelAulas.setMaximumSize(new java.awt.Dimension(400, 280));
        painelAulas.setMinimumSize(new java.awt.Dimension(400, 280));
        painelAulas.setPreferredSize(new java.awt.Dimension(400, 280));

        botaoVoltarInicio.setLabel("Voltar");
        botaoVoltarInicio.setPreferredSize(new java.awt.Dimension(80, 25));
        botaoVoltarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarInicioActionPerformed(evt);
            }
        });

        tabPrincipal.addTab("Salario", tabAula1);
        tabPrincipal.addTab("IMC", tabAula2);

        javax.swing.GroupLayout painelAulasLayout = new javax.swing.GroupLayout(painelAulas);
        painelAulas.setLayout(painelAulasLayout);
        painelAulasLayout.setHorizontalGroup(
            painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAulasLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(botaoVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        painelAulasLayout.setVerticalGroup(
            painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAulasLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(botaoVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelAulasLayout.createSequentialGroup()
                    .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(painelAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        // TODO add your handling code here:
        painelMain.setVisible(false);
        painelAulas.setVisible(true);
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoVoltarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarInicioActionPerformed
        // TODO add your handling code here:
        painelAulas.setVisible(false);
        painelMain.setVisible(true);
    }//GEN-LAST:event_botaoVoltarInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*
            Autor: @Rodrigo
            Descrição: Seleciona um tema personalidado
            Biblioteca: flatlaf-demo-3.4.jar
            */
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            //    if ("Nimbus".equals(info.getName())) {
            //       javax.swing.UIManager.setLookAndFeel(info.getClassName());
            //        break;
            //    }
            //}
        //} catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desutilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desutilidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoVoltarInicio;
    private javax.swing.JPanel painelAulas;
    private javax.swing.JPanel painelMain;
    private javax.swing.JTabbedPane tabAula1;
    private javax.swing.JTabbedPane tabAula2;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JLabel tituloMain;
    // End of variables declaration//GEN-END:variables
}
